services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6378:6378"
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6378/0